services:
  - type: web
    name: laura-nails-v2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER
        value: laura.laura
      - key: ADMIN_PASSWORD
        sync: false
